---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      expose: "true"
      app: camel-quarkus
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.example
    name: camel-quarkus
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: camel-quarkus
      provider: fabric8
      group: org.example
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: camel-quarkus
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.example
    name: camel-quarkus
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      app: camel-quarkus
      provider: fabric8
      group: org.example
    strategy:
      rollingParams:
        timeoutSeconds: 3600
      type: Rolling
    template:
      metadata:
        labels:
          app: camel-quarkus
          provider: fabric8
          version: 1.0.0-SNAPSHOT
          group: org.example
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: example/camel-quarkus:latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          name: quarkus
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            successThreshold: 1
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: camel-quarkus
      provider: fabric8
      version: 1.0.0-SNAPSHOT
      group: org.example
    name: camel-quarkus
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: camel-quarkus
